name: Backend-CICD

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          apt-get update && apt-get install --no-install-recommends -y binutils vim-tiny libproj-dev gdal-bin python3-gdal
          pip install -r requirements.txt
      - name: run django test
        run: |
          python shop/manage.py test
        
  build:
    runs-on: ubuntu-latest
    container: docker:20.10.17
    needs: test
    steps:
      - name: build
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          docker build -t techwithmike/shop:v1.0 .
          docker push techwithmike/shop:v1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          KEY: ${{ secrets.PROD_SSHKEY }}
          script: >
            cd ${{ secrets.PROD_PROJECT_PATH }} 
            && git pull 
            && ./mng-api.sh up